INSERT INTO tblRoles (name)
SELECT 'SUPER USER'
WHERE NOT EXISTS (SELECT 1 FROM tblRoles WHERE name = 'SUPER USER');

INSERT INTO tblRoles (name)
SELECT 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM tblRoles WHERE name = 'ADMIN');

INSERT INTO tblRoles (name)
SELECT 'STANDARD'
WHERE NOT EXISTS (SELECT 1 FROM tblRoles WHERE name = 'STANDARD');
