CREATE TABLE IF NOT EXISTS tblUsers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    username_normalized VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    type INTEGER NOT NULL,
    accountExpiry TIMESTAMP NULL,
    emailAddress VARCHAR(255),
    passwordNoExpire BOOLEAN NOT NULL,
    lastLogin TIMESTAMP NULL,
    incorrectLoginAttempts INTEGER NOT NULL,
    lockoutUntil TIMESTAMP NULL,
    bypassLockout BOOLEAN NOT NULL,
    changePasswordNextLogin BOOLEAN NOT NULL,
    fullName VARCHAR(255),
    bypassDocumentSecurity BOOLEAN NOT NULL,
    isExternalIdentity BOOLEAN NOT NULL
);

ALTER TABLE tblUsers ADD COLUMN IF NOT EXISTS lockoutUntil TIMESTAMP;

CREATE TABLE IF NOT EXISTS tblAuthSessions (
    token VARCHAR(64) PRIMARY KEY,
    userId BIGINT NOT NULL,
    createdAt TIMESTAMP NOT NULL,
    lastAccessedAt TIMESTAMP NOT NULL,
    expiresAt TIMESTAMP NOT NULL,
    CONSTRAINT fk_tblAuthSessions_user FOREIGN KEY (userId) REFERENCES tblUsers(id)
);

CREATE INDEX IF NOT EXISTS idx_tblAuthSessions_expiresAt ON tblAuthSessions (expiresAt);
CREATE INDEX IF NOT EXISTS idx_tblAuthSessions_lastAccessedAt ON tblAuthSessions (lastAccessedAt);
CREATE INDEX IF NOT EXISTS idx_tblAuthSessions_userId ON tblAuthSessions (userId);

CREATE TABLE IF NOT EXISTS tblPasswordResetSessions (
    userId BIGINT PRIMARY KEY,
    token VARCHAR(64) NOT NULL UNIQUE,
    expiresAt TIMESTAMP NOT NULL,
    CONSTRAINT fk_tblPasswordResetSessions_user FOREIGN KEY (userId) REFERENCES tblUsers(id)
);

CREATE INDEX IF NOT EXISTS idx_tblPasswordResetSessions_expiresAt ON tblPasswordResetSessions (expiresAt);

CREATE TABLE IF NOT EXISTS tblAuthenticationRateLimits (
    bucket_key VARCHAR(96) PRIMARY KEY,
    windowStartedAt TIMESTAMP NOT NULL,
    attemptCount INTEGER NOT NULL,
    blockedUntil TIMESTAMP NULL,
    expiresAt TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tblAuthenticationRateLimits_expiresAt
    ON tblAuthenticationRateLimits (expiresAt);

CREATE TABLE IF NOT EXISTS tblRoles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tblUserRoles (
    userId BIGINT NOT NULL,
    roleId BIGINT NOT NULL,
    PRIMARY KEY (userId, roleId),
    CONSTRAINT fk_tblUserRoles_user FOREIGN KEY (userId) REFERENCES tblUsers(id),
    CONSTRAINT fk_tblUserRoles_role FOREIGN KEY (roleId) REFERENCES tblRoles(id)
);

CREATE TABLE IF NOT EXISTS tblGroups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tblGroupUsers (
    groups_id BIGINT NOT NULL,
    users_id BIGINT NOT NULL,
    PRIMARY KEY (groups_id, users_id),
    FOREIGN KEY (groups_id) REFERENCES tblGroups(id),
    FOREIGN KEY (users_id) REFERENCES tblUsers(id)
);

-- Backward compatibility for older schemas that created GroupEntity_id
ALTER TABLE tblGroupUsers ADD COLUMN IF NOT EXISTS GroupEntity_id BIGINT;
ALTER TABLE tblGroupUsers ADD COLUMN IF NOT EXISTS groups_id BIGINT;
UPDATE tblGroupUsers SET groups_id = GroupEntity_id WHERE groups_id IS NULL;

CREATE TABLE IF NOT EXISTS tblGroupParents (
    groupId BIGINT NOT NULL,
    parentGroupId BIGINT NOT NULL,
    PRIMARY KEY (groupId, parentGroupId),
    FOREIGN KEY (groupId) REFERENCES tblGroups(id),
    FOREIGN KEY (parentGroupId) REFERENCES tblGroups(id)
);

CREATE TABLE IF NOT EXISTS tblGroupRoles (
    groupId BIGINT NOT NULL,
    roleId BIGINT NOT NULL,
    PRIMARY KEY (groupId, roleId),
    FOREIGN KEY (groupId) REFERENCES tblGroups(id),
    FOREIGN KEY (roleId) REFERENCES tblRoles(id)
);

CREATE TABLE IF NOT EXISTS tblResources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    pathPrefix VARCHAR(255) NOT NULL,
    httpMethod VARCHAR(16) NOT NULL DEFAULT '*',
    CONSTRAINT ck_tblResources_httpMethod_canonical
        CHECK (httpMethod = '*' OR httpMethod = UPPER(TRIM(httpMethod))),
    CONSTRAINT ux_tblResources_path_method UNIQUE (pathPrefix, httpMethod)
);

CREATE INDEX IF NOT EXISTS idx_tblResources_path_method
    ON tblResources (pathPrefix, httpMethod);

CREATE TABLE IF NOT EXISTS tblRoleResources (
    roleId BIGINT NOT NULL,
    resourceId BIGINT NOT NULL,
    PRIMARY KEY (roleId, resourceId),
    FOREIGN KEY (roleId) REFERENCES tblRoles(id),
    FOREIGN KEY (resourceId) REFERENCES tblResources(id)
);

CREATE TABLE IF NOT EXISTS tblOrders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId BIGINT,
    symbol VARCHAR(255),
    side VARCHAR(32),
    quantity DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    status VARCHAR(64),
    createdAt TIMESTAMP,
    closedAt TIMESTAMP,
    closePrice DOUBLE PRECISION,
    aiPrediction VARCHAR(32),
    bullScore DOUBLE PRECISION
);

ALTER TABLE tblOrders ADD COLUMN IF NOT EXISTS userId BIGINT;
ALTER TABLE tblOrders ADD COLUMN IF NOT EXISTS status VARCHAR(64);
ALTER TABLE tblOrders ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP;
ALTER TABLE tblOrders ADD COLUMN IF NOT EXISTS closedAt TIMESTAMP;
ALTER TABLE tblOrders ADD COLUMN IF NOT EXISTS closePrice DOUBLE PRECISION;
ALTER TABLE tblOrders ADD COLUMN IF NOT EXISTS aiPrediction VARCHAR(32);
ALTER TABLE tblOrders ADD COLUMN IF NOT EXISTS bullScore DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS tblTrades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId BIGINT,
    orderId BIGINT,
    symbol VARCHAR(255),
    side VARCHAR(32),
    executionType VARCHAR(32),
    quantity DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP
);

ALTER TABLE tblTrades ADD COLUMN IF NOT EXISTS userId BIGINT;
ALTER TABLE tblTrades ADD COLUMN IF NOT EXISTS orderId BIGINT;
ALTER TABLE tblTrades ADD COLUMN IF NOT EXISTS side VARCHAR(32);
ALTER TABLE tblTrades ADD COLUMN IF NOT EXISTS executionType VARCHAR(32);
CREATE INDEX IF NOT EXISTS idx_tblTrades_user_timestamp ON tblTrades (userId, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_tblTrades_order_execution ON tblTrades (orderId, executionType);

CREATE TABLE IF NOT EXISTS tblUserProperties (
    userId BIGINT NOT NULL,
    propertyName VARCHAR(255) NOT NULL,
    value VARCHAR(255),
    PRIMARY KEY (userId, propertyName),
    FOREIGN KEY (userId) REFERENCES tblUsers(id)
);

CREATE TABLE IF NOT EXISTS market_bars (
    symbol VARCHAR(32) NOT NULL,
    bucket TIMESTAMP NOT NULL,
    open DOUBLE PRECISION NOT NULL,
    high DOUBLE PRECISION NOT NULL,
    low DOUBLE PRECISION NOT NULL,
    close DOUBLE PRECISION NOT NULL,
    volume DOUBLE PRECISION NOT NULL,
    source VARCHAR(64) NOT NULL DEFAULT 'tradernet',
    PRIMARY KEY (symbol, bucket)
);

CREATE INDEX IF NOT EXISTS idx_market_bars_symbol_bucket_desc ON market_bars (symbol, bucket DESC);
