ALTER TABLE tblUsers
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('tblusers', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM tblUsers), 0), 1),
    EXISTS (SELECT 1 FROM tblUsers)
);
