package com.tradernet.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents a trading signal generated by a strategy or algorithm.
 */
@Entity
@Table(name = "tblSignals")
public class SignalEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String symbol;

    @Enumerated(EnumType.STRING)
    private Type type;

    private double confidence;

    public SignalEntity() {
    }

    /**
     * Constructs a Signal.
     *
     * @param symbol     the symbol the signal applies to
     * @param type       type of signal (BUY, SELL, HOLD)
     * @param confidence confidence level between 0 and 1
     */
    public SignalEntity(String symbol, Type type, double confidence) {
        this.symbol = symbol;
        this.type = type;
        this.confidence = confidence;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public Type getType() {
        return type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    public double getConfidence() {
        return confidence;
    }

    public void setConfidence(double confidence) {
        this.confidence = confidence;
    }

    @Override
    public String toString() {
        return type + " signal for " + symbol + " (confidence=" + confidence + ")";
    }

    /**
     * Possible types of signals.
     */
    public enum Type {BUY, SELL, HOLD}
}
