package com.tradernet.model;

/**
 * Represents a trading signal generated by a strategy or algorithm.
 */
public class Signal {

    private final String symbol;
    private final Type type;
    private final double confidence;
    
    /**
     * Constructs a Signal.
     *
     * @param symbol     the symbol the signal applies to
     * @param type       type of signal (BUY, SELL, HOLD)
     * @param confidence confidence level between 0 and 1
     */
    public Signal(String symbol, Type type, double confidence) {
        this.symbol = symbol;
        this.type = type;
        this.confidence = confidence;
    }

    public String getSymbol() {
        return symbol;
    }

    public Type getType() {
        return type;
    }

    public double getConfidence() {
        return confidence;
    }

    @Override
    public String toString() {
        return type + " signal for " + symbol + " (confidence=" + confidence + ")";
    }

    /**
     * Possible types of signals.
     */
    public enum Type {BUY, SELL, HOLD}
}
