CREATE TABLE IF NOT EXISTS tblUsers (
    id BIGINT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255),
    type INTEGER NOT NULL,
    accountExpiry TIMESTAMP NULL,
    emailAddress VARCHAR(255),
    passwordNoExpire BOOLEAN NOT NULL,
    lastLogin TIMESTAMP NULL,
    incorrectLoginAttempts INTEGER NOT NULL,
    bypassLockout BOOLEAN NOT NULL,
    changePasswordNextLogin BOOLEAN NOT NULL,
    fullName VARCHAR(255),
    bypassDocumentSecurity BOOLEAN NOT NULL,
    isExternalIdentity BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS tblRoles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS tblUserRoles (
    userId BIGINT NOT NULL,
    roleId BIGINT NOT NULL,
    PRIMARY KEY (userId, roleId),
    CONSTRAINT fk_tblUserRoles_user FOREIGN KEY (userId) REFERENCES tblUsers(id),
    CONSTRAINT fk_tblUserRoles_role FOREIGN KEY (roleId) REFERENCES tblRoles(id)
);

CREATE TABLE IF NOT EXISTS tblPasswords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId BIGINT,
    lastChanged TIMESTAMP,
    passwordHash VARCHAR(255),
    CONSTRAINT fk_tblPasswords_user FOREIGN KEY (userId) REFERENCES tblUsers(id)
);

CREATE TABLE IF NOT EXISTS tblGroups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS tblGroupUsers (
    GroupEntity_id BIGINT NOT NULL,
    users_id BIGINT NOT NULL,
    PRIMARY KEY (GroupEntity_id, users_id),
    FOREIGN KEY (GroupEntity_id) REFERENCES tblGroups(id),
    FOREIGN KEY (users_id) REFERENCES tblUsers(id)
);

CREATE TABLE IF NOT EXISTS tblGroupParents (
    groupId BIGINT NOT NULL,
    parentGroupId BIGINT NOT NULL,
    PRIMARY KEY (groupId, parentGroupId),
    FOREIGN KEY (groupId) REFERENCES tblGroups(id),
    FOREIGN KEY (parentGroupId) REFERENCES tblGroups(id)
);

CREATE TABLE IF NOT EXISTS tblOrders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(255),
    side VARCHAR(32),
    quantity DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS tblSignals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(255),
    type VARCHAR(32),
    confidence DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS tblTrades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(255),
    quantity DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tblUserProperties (
    userId BIGINT NOT NULL,
    propertyName VARCHAR(255) NOT NULL,
    value VARCHAR(255),
    PRIMARY KEY (userId, propertyName),
    FOREIGN KEY (userId) REFERENCES tblUsers(id)
);


INSERT INTO tblRoles (name)
SELECT 'SUPER USER'
WHERE NOT EXISTS (SELECT 1 FROM tblRoles WHERE name = 'SUPER USER');

INSERT INTO tblRoles (name)
SELECT 'ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM tblRoles WHERE name = 'ADMIN');

INSERT INTO tblRoles (name)
SELECT 'STANDARD'
WHERE NOT EXISTS (SELECT 1 FROM tblRoles WHERE name = 'STANDARD');
