package com.tradernet.jpa.core;

/**
 * Represents a trading signal generated by the TraderNet system.
 * Each signal contains the symbol being traded, the price at the time
 * of the signal, and the intended action (BUY, SELL, or HOLD).
 */
public class TradingSignal {

    // The trading symbol (e.g., "AAPL", "BTCUSD")
    private final String symbol;
    // The price at which the signal was generated
    private final double price;
    // The action associated with this signal
    private final Action action;

    /**
     * Constructs a TradingSignal with the given parameters.
     *
     * @param symbol The trading symbol
     * @param price  The price associated with the signal
     * @param action The action (BUY, SELL, HOLD)
     */
    public TradingSignal(String symbol, double price, Action action) {
        this.symbol = symbol;
        this.price = price;
        this.action = action;
    }

    /**
     * Returns the trading symbol of this signal.
     *
     * @return symbol
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Returns the price at which the signal was generated.
     *
     * @return price
     */
    public double getPrice() {
        return price;
    }

    /**
     * Returns the action associated with this signal.
     *
     * @return action
     */
    public Action getAction() {
        return action;
    }

    @Override
    public String toString() {
        return "TradingSignal{" +
            "symbol='" + symbol + '\'' +
            ", price=" + price +
            ", action=" + action +
            '}';
    }

    /**
     * The type of action that the trading signal represents.
     */
    public enum Action {
        BUY,    // Signal to buy the asset
        SELL,   // Signal to sell the asset
        HOLD    // Signal to hold / do nothing
    }
}
